export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_DP_URL = 'SET_DP_URL';

export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';

export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';
export const GET_ALL_POSTS_START = 'GET_ALL_POSTS_START';
export const ADD_TO_POSTS = 'ADD_TO_POSTS';

export const GET_COMPOSE_CHAT_LIST_SUCCESS = 'GET_COMPOSE_CHAT_LIST_SUCCESS';
export const GET_CHAT_HEAD_LIST_SUCCESS = 'GET_CHAT_HEAD_LIST_SUCCESS';
export const SET_MESSAGES = 'SET_MESSAGES';
